name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Validate Docker Compose
      run: docker compose config

    - name: Build Docker Images
      run: docker compose build

    - name: Check code formatting (PEP8)
      uses: psf/black@stable
      with:
        options: "--check --diff backend/"
      continue-on-error: true # Non-blocking for now, just to show intent
